---
kind: pipeline
type: docker
name: build-home-docs

steps:
- name: build-docs
  image: squidfunk/mkdocs-material:9.1.17
  pull: if-not-exists
  volumes:
  - name: site
    path: /site
  - name: site-st1tru
    path: /site-st1tru
  commands:
    - pip install -U -r ./requirements.txt
    - mkdocs build
    - cp -r site/ /site
    - cp -r site/ /site-st1tru
    - chown 1000:1000 /site
    - chown 1000:1000 /site-st1tru
    - chmod -R 777 /site
    - chmod -R 777 /site-st1tru
  when:
    event: push
    branch: main

- name: check-feature
  image: squidfunk/mkdocs-material:9.1.17
  pull: if-not-exists
  volumes:
  - name: site
    path: /site
  commands:
    - pip install -U -r ./requirements.txt
    - mkdocs build
    - cp -r site/ /site
    - chown 1000:1000 /site
    - chmod -R 777 /site
  when:
    event: push
    branch: states/*

- name: telgram_notify
  image: appleboy/drone-telegram
  when:
    status:
      #- success
      - failure
  settings:
    # The secrets below can be entered from the Drone UI for this repo
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chat_id
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{/success}}

volumes:
- name: site
  host:
    path: /opt/appdata/mkdocswiki
- name: site-st1tru
  host:
    path: /opt/appdata/nginx/st1t.ru