---
kind: pipeline
type: docker
name: build-home-docs

steps:
- name: build main
  image: git.st1t.ru/thest1tch/mkdocs-material:latest
  pull: if-not-exists
  volumes:
  - name: site-st1tru
    path: /site
  commands:
    - mkdocs build
    - cp -r site/ /site
    - chown 1000:1000 /site
    - chmod -R 777 /site
  when:
    event: 
      - push
    branch: 
      - main

- name: build states
  image: git.st1t.ru/thest1tch/mkdocs-material:latest
  pull: if-not-exists
  volumes:
  - name: site-dev
    path: /site
  commands:
    - mkdocs build
    - cp -r site/ /site
    - chown 1000:1000 /site
    - chmod -R 777 /site
  when:
    event: 
      - push
    branch: 
      - states/*

volumes:
- name: site-st1tru
  host:
    path: /opt/appdata/nginx/st1t.ru
- name: site-dev
  host:
    path: /opt/appdata/nginx/dev.thest1tch.ru