---
kind: pipeline
type: docker
name: build-home-docs

steps:
  - name: build-docs
    image: squidfunk/mkdocs-material:9.1.15
    pull: if-not-exists
    volumes:
      - name: docs
        path: /opt/appdata/mkdocswiki
    commands:
      - pip install -U -r ./requirements.txt
      - mkdocs build
      - cp -r /drone/src/site /docs
      - chmod -R 777 /docs
    when:
      event: push
      branch: main
      
#volumes:
#  - name: docs
#    host:
#      path: /opt/appdata/mkdocswiki