when:
  - event: push
    branch: main


steps:
  - name: build
    image: git.st1t.ru/thest1tch/mkdocs-material:latest
    commands:
      - mkdocs build --clean
      #- ls -l site/
      #- cp -r site/ /site
      #- chown 1000:1000 /site
      #- chmod -R 777 /site  

  - name: deploy
    image: alpine:latest
    volumes:
      - /opt/appdata/nginx/st1t.ru/site:/site
    commands:
      - apt install rsync -y
      - rsync -avz --delete site/* /site/ #cp -r site/* /site/
      - echo "Deployment complete."
      