site_name: St1t.ru
site_url: https://st1t.ru
repo_url: https://git.st1t.ru/thest1tch/docs
repo_name: thest1tch/docs
edit_uri: edit/main/docs/

nav:
  - Привет!: index.md
  - 🐳 Docker: 
    - Подготовка:
      - Install: docker.md
    - В начале:
      - Traefik: docker-compose/traefik.md
      - Traefik Forward Auth: docker-compose/traefik-forward-auth.md
    - Сервисы: 
      - Linx Server: docker-compose/linx-server.md
      - Samba: docker-compose/samba.md
      - Redis: docker-compose/redis.md
      - MotionEye: docker-compose/motioneye.md
      - Media Server:
        - Plex: docker-compose/plex.md
        - Plex Meta Manager: docker-compose/plex-mm.md
        - Plex Trakt Sync: docker-compose/plextraktsync.md
  - Ubuntu 22:
      - HPE:
          - Management Component Pack: ubuntu/hpe/hpe-mcp.md
      - MariaDB: ubuntu/mariadb.md
      - Telegraf: ubuntu/telegraf.md
      - Docker+UFW: ubuntu/docker-ufw.md
      - Монтирование CIFS: ubuntu/mount-cifs.md
  - Proxmox:
      - CT Template: proxmox/ct-template.md
  - Помойка:
    - SSL для сайта: other/ssl-for-site.md
    - Ubuntu bash aliases: other/ubuntu-bash-aliases.md
    - ТСД:
      - Прошивка MC9090 на CE7.0: 
        - other/tsd/index.md
        - Переустановка ОС: other/tsd/reinstall-ce7.md
        - Настройка ТСД: other/tsd/configure-ce7.md
        - Настройка Wi-Fi: other/tsd/configure-wifi.md
        - Настройка TelnetCE: other/tsd/configure-telnetce.md
        - Установка TelnetCE: other/tsd/install-telnetce.md
    - Synology:
      - HPE Microserver Gen10: other/synology/install-hpe-ms-gen10
        
  - Сеть:
    - Mikrotik:
      - Wireguard: network/mikrotik/wireguard.md
    - Ubiquiti:
      - Добавление новой точки: network/ubi/add-new-ap.md
      - Ошибка обновления: network/ubi/failed-update.md
  - Блог:
    - Начальная: blog/index.md
    - Traefik FA: blog/posts/traefik-fa.md

theme:
  name: material
  #custom_dir: overrides
  language: ru
  #logo: images/site/logo.png
  favicon: images/assets/favicon.png
  icon:
    repo: simple/gitea
    logo: fontawesome/regular/folder-open
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Авто

    # Toggle light mode 
    - media: "(prefers-color-scheme: light)"       
      scheme: default
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-7
        name: Испепели мои глаза!

    # Toggle dark mode  
    - media: "(prefers-color-scheme: dark)"      
      scheme: slate
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-4
        name: Я люблю свои глаза!

  font:
    code: Jet Brains Mono

  features:
    #- navigation.instant
    - navigation.sections # prevents collapsible sections
    - navigation.indexes # section index pages
    - navigation.expand #expands sections by default
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.pruning
    - navigation.path
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - toc.follow
  # insiders only
  #   - search.suggest

plugins:
  - search:
      lang: 
        - ru
        - en
  - glightbox
  - blogging:
      dirs: # The directories to be included
        - blog

markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: false
      toc_depth: 3
  - pymdownx.highlight: # code highlighting
      linenums: true
  - pymdownx.tabbed: # enables tabs for embedded blocks
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2023 &copy; TheSt1tch - Licensed under GPLv3

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xtsgTBf