site_name: St1t.ru
site_url: https://st1t.ru/
repo_url: https://git.st1t.ru/thest1tch/docs
repo_name: thest1tch/docs
edit_uri: edit/main/docs/

nav:
  - Привет!: index.md
  - 🐳 Docker: 
    - Подготовка:
      - Установка: docker/install.md
      - Безопасность: docker/security.md
      - Ошибки: docker/error.md
      - Docker Compose:
        - Healthcheck: docker/compose/healthcheck.md
        - Profiles: docker/compose/profiles.md
      - Traefik: 
        - docker/traefik/index.md
        - Error Pages: docker/traefik/errorpages.md
        - Forward Auth: docker/traefik/forward-auth.md
        - TCP Route: docker/traefik/tcp-routes.md
    - Сервисы: 
      - Drone CI: docker/drone.md
      - Dockge: docker/dockge.md
      - Gitea: docker/gitea.md
      #- Grafana+Prometheus: docker/grafana-prometheus.md
      - Grafana:
        - index.md
        - Prometheus: docker/grafana/prometheus.md
      - HandBrake: docker/handbrake.md
      - Homarr: docker/homarr.md
      - Homepage: docker/homepage.md
      - Linx Server: docker/linx-server.md
      - MotionEye: docker/motioneye.md
      - Nextcloud:
        - docker/nextcloud/index.md
        - During Scan: docker/nextcloud/during-scan.md
        - PHP imagick: docker/nextcloud/php-imagick.md
        - Cron: docker/nextcloud/cron.md
        - Проблемы с data: docker/nextcloud/problems-after-moving-data-folder.md
        - OCC: docker/nextcloud/occ-files-scan.md
        - OIDC-login: docker/nextcloud/oidc-login.md
      - Photoprism: docker/photoprism.md
      - Pictshare: docker/pictshare.md
      - Plex: 
        - docker/plex/index.md
        - Autoscan: docker/plex/autoscan.md
        - Jackett: docker/plex/jackett.md
        #- Overseerr:
        - Plex Meta Manager: docker/plex/plex-mm.md
        - Plex Trakt Sync: docker/plex/plextraktsync.md
        - Prowlarr: docker/plex/prowlarr.md
        - Radarr: docker/plex/radarr.md
        - Sonarr: docker/plex/sonarr.md
        - Решение проблем: docker/plex/troubleshooting.md
      - Redis: docker/redis.md
      - Samba: docker/samba.md
      - Socket Proxy: docker/socket-proxy.md
      - Syncthing: docker/syncthing.md
      - Uptime Kuma: docker/uptime-kuma.md
      - WikiJS: docker/wikijs.md
    - Игровые сервера:
      - Valheim: docker/games/valheim.md
      - Factorio: docker/games/factorio.md
      - ARK Survival Evolved: docker/games/ark-se.md
  - Ubuntu Server:
    - ubuntu/index.md
    - Команды: ubuntu/commands.md
    - Ошибки консоли: ubuntu/errors.md
    - Добавление диска: ubuntu/add-disk.md
    - Расширение раздела: ubuntu/resize-part.md
    - Добавление S3: ubuntu/add-s3.md
    - LVM: ubuntu/lvm.md
    - fsck: ubuntu/fsck.md
    - Docker+UFW: ubuntu/docker-ufw.md
    - Монтирование CIFS: ubuntu/mount-cifs.md
    - Ubuntu bash aliases: ubuntu/bash-aliases.md
    - Установка xRDP: ubuntu/xrdp.md
    - Использование Proxy: ubuntu/proxy-system.md
    - Watchdog: ubuntu/watchdog.md
    - Копирование через SCP: ubuntu/scp.md
    - Обновление дистрибутива: ubuntu/upgrade-dist.md
    - Русский язык в консоли: ubuntu/add-locale-russian.md
    - Отключение AppArmor: ubuntu/disable-apparmor.md
    - Защита Linux: ubuntu/secure-linux.md
    - Backup:
      - Google Диск: ubuntu/backup/google.md
      - Yandex: ubuntu/backup/yandex.md
      - Базы данных: ubuntu/backup/db.md
    - WebDAV:
      - Google Диск: ubuntu/webdav/google.md
      - Yandex: ubuntu/webdav/yandex.md
    - Софт:
      - MariaDB: ubuntu/mariadb.md
      - Telegraf: ubuntu/telegraf.md
      - Redis: ubuntu/redis.md
      - HPE:
        - Management Component Pack: ubuntu/hpe/hpe-mcp.md
      - NCDU: ubuntu/ncdu.md
      - btop: ubuntu/btop.md
      - ctop: ubuntu/ctop.md
  - Software:
    - Powershell:
      - software/powershell/index.md
      - Active Directiry: software/powershell/ad.md
      - Stop-Process: software/powershell/stop-process.md
      - Count-Pages: software/powershell/count-pages.md
      - Send-Mail: software/powershell/send-mail.md
      - Обновление времени: software/powershell/update-time.md
      - Get-Content: software/powershell/get-content.md
    - Chrome:
      - Download bar: software/chrome/download-bar.md
      - Блокировка медиакнопок: software/chrome/block-mediabutton.md
    - Windows:
      - Servers:
        - Удаление RUS US: software/win/serv/rusus.md
        - CleanMGR: software/win/serv/cleanmgr.md
        - SPP + Hyper-V: software/win/serv/spp-hyperv.md
        - VHD: software/win/serv/vhd.md
        - WIM в ESD: software/win/serv/wim-esd.md
        - SQL Server: software/win/serv/mssql.md
      - Desktop:
        - Send To: software/win/desk/sendto.md
        - Удаление hiberfil.sys: software/win/desk/del-hiberfil.md
        - Удаление папок в МойКомп: software/win/desk/del-mycomp.md
        - Удаление папки WindowsApps: software/win/desk/del-winapps.md
        - Получить код OEM: software/win/desk/get-key-oem.md
        - Не работает клавиша PrnScr: software/win/desk/prnscr.md
        - TWINUI в свойствах файла: software/win/desk/twinui.md
        - KMS: software/win/desk/kms.md
        - Установка DialUX: software/win/desk/dialux.md
    - VS Code:
      - Запрос учетных данных Git: software/vscode/asking-git-credentials.md
  - Hardware:
    - IP Телефоны:
      - Grandstream:
        - Provisioning через TFTP: hardware/phone/grandstream/provisioning.md
        - Пример конфигурации: hardware/phone/grandstream/example-config.md
      - Ipecs-MG:
        - Общие настройки: hardware/phone/ipecs-mg/general.md
        - Книги: hardware/phone/ipecs-mg/books.md
        - Голосовые приветствия: hardware/phone/ipecs-mg/voice.md
    - Принтеры:
      - Kyocera: hardware/printers/kyocera.md      
    - ТСД:
      - hardware/tsd/index.md
      - Переустановка ОС:
        - CE 5.0: hardware/tsd/reinstall-os/ce5.md
        - CE 7.0: hardware/tsd/reinstall-os/ce7.md
        - WM 6.1: hardware/tsd/reinstall-os/m61.md
      - Настройка ТСД: hardware/tsd/config-ce.md
      - Настройка Wi-Fi: hardware/tsd/config-wifi.md
      - Настройка TelnetCE: hardware/tsd/config-telnetce.md
      - Установка TelnetCE: hardware/tsd/install-telnetce.md
      - Траблшутинг: hardware/tsd/troubleshooting.md
    - Synology:
      - HPE Microserver Gen10: hardware/synology/install-hpe-ms-gen10.md
      - SSO Login: hardware/synology/sso-client.md
      - Update CA root Cert: hardware/synology/update-ca-root-cert.md
    - HPE iLo: hardware/hpe-ilo.md
  - Proxmox:
    - Proxmox VE:
      - proxmox/index.md
      - CT Template: proxmox/ct-template.md
      - Nvidia LXC: proxmox/nvidia-lxc.md
      - Добавление диска к VM: proxmox/add-disk-vm.md
  - Умный дом:
    - Home Assistant:
      - Установка на Debian: smart-home/hass/install-hass-debian.md
      - Addons:
        - Zigbee2mqtt: smart-home/hass/zigbee2mqtt.md
      - Package: 
        - smart-home/hass/package/index.md
        - Будильник: smart-home/hass/package/budilnik.md
      - Device:
        - Xiaomi Airpurifier: smart-home/hass/device/xiaomi-airpurifier.md
      - Автоматизации:
        - Триггеры:
          - Время: smart-home/hass/automation/trigger/time.md
    - Wirenboard:
      - Новый контроллер: smart-home/wirenboard/new-controller.md
      - Термостат Hessway: smart-home/wirenboard/termostat-hessway.md
      - Полезные ссылки: smart-home/wirenboard/useful-links.md
  - Другое:
    - Полезные ресурсы: other/helpfull-links.md
    - Закрыть фишинговый сайт: other/close-phishing-site.md
    - SSL для сайта: other/ssl-for-site.md
    - Self Hosted: other/self-hosted.md   
    - Office:
      - Excel:
        - other/office/excel/index.md
        - VBA Защита страницы: other/office/excel/vba-security-page.md
        - VBA Исправление примечаний: other/office/excel/vba-align-comments.md
        - VBA Создание файла: other/office/excel/vba-create-file.md
        - VBA Открытие файла: other/office/excel/vba-open-file.md
        - VBA Отправка почты: other/office/excel/vba-send-email.md
        - VBA Прогресс бар: other/office/excel/vba-progress-bar.md
        - VBA Удаление пароля: other/office/excel/vba-remove-pass.md
      - Outlook:
        - Ошибки: other/office/outlook/error.md
  - Сеть:
    - Утилиты:
      - Wtraf: network/tools/wtraf.md
      - Nmap: network/tools/nmap.md
    - Mikrotik:
      - network/mikrotik/index.md
      - Wireguard: network/mikrotik/wireguard.md
      - 4G Модем: network/mikrotik/4g.md
      - Cloud Hosted Router: network/mikrotik/chr.md
      - DHCP: network/mikrotik/dhcp.md
      - Split-DNS: network/mikrotik/split-dns.md
      - Hairpin NAT: network/mikrotik/hairpin-nat.md
      - UPnP: network/mikrotik/upnp.md
      - eBGP: network/mikrotik/ebgp.md
      - Маркировка трафика: network/mikrotik/mark-traffik.md
      #- Обход блокировок: network/mikrotik/unblock-site.md
    - Ubiquiti:
      - Добавление новой точки: network/ubi/add-new-ap.md
      - Ошибка обновления: network/ubi/failed-update.md
  - Игры:
    - ARK Survival Evolved:
      - Админские команды: games/ark/admin-commands.md
    - Factorio:
      - games/factorio/index.md
      - Мои чертежи: games/factorio/my-prints.md
      - Чертежи сообщества: games/factorio/blueprints.md
    - Payday 2:
      - VanillaHUD Plus: games/payday2/hud.md
    - Path of Exile: 
      - Ссылки: games/path-of-exile/links.md
  - Блог:
    - Blog: blog/index.md

theme:
  name: material
  theme_dir: overrides
  language: ru
  logo: images/st1t_white.png
  favicon: images/st1t_blue.png
  icon:
    repo: simple/gitea
    #logo: images/st1t_white.png
  palette:
  
    # Toggle light mode 
    - media: "(prefers-color-scheme: light)"       
      scheme: default
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-7
        name: Испепели мои глаза!

    # Toggle dark mode  
    - media: "(prefers-color-scheme: dark)"      
      scheme: slate
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-4
        name: Я люблю свои глаза!

  font:
    code: Jet Brains Mono

  features:
    - navigation.sections # prevents collapsible sections
    - navigation.indexes # section index pages
    #- navigation.expand #expands sections by default
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - navigation.path
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - toc.follow

plugins:
  #- meta
  - search:
      lang: 
        - ru
        - en
  - glightbox
  - blog:
      post_url_format: "{date}/{slug}"
  - git-revision-date-localized:
      type: custom
      custom_format: "%d.%m.%Y"
      fallback_to_build_date: true
      enable_creation_date: true
      locale: ru
      exclude:
        - index.md  

markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: false
      toc_depth: 3
  - pymdownx.highlight: # code highlighting
      linenums: false
  - pymdownx.tabbed: # enables tabs for embedded blocks
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

extra:
  analytics:
    provider: google
    property: G-E6GYT2D13K

copyright: 2025 &copy; TheSt1tch - Licensed under GPLv3