site_name: Docs St1t.ru
repo_url: https://git.st1t.ru/thest1tch/docs
repo_name: thest1tch/docs
edit_uri: edit/main/docs/

nav:
  - Привет!: index.md
  - 🐳 Docker Compose: 
    - Install Docker Compose: docker-compose.md
    - Linx Server: docker-compose/linx-server.md
    - Samba: docker-compose/samba.md
    - Redis: docker-compose/redis.md
    - MotionEye: docker-compose/motioneye.md
    - Media Server:
      - Plex: docker-compose/plex.md
      - Plex Meta Manager: docker-compose/plex-mm.md
    - Traefik:
      - Traefik Forward Auth: docker-compose/traefik-forward-auth.md
  - :Ubuntu: Ubuntu 22:
      - MariaDB: ubuntu/mariadb.md
  - Помойка:
    - SSL для сайта: other/ssl-for-site.md
    - Ubuntu bash aliases: other/ubuntu-bash-aliases.md

theme:
  name: material
  #custom_dir: overrides
  language: ru
  #logo: images/site/logo.png
  favicon: images/assets/favicon.png
  icon:
    repo: simple/gitea
    logo: fontawesome/regular/folder-open
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Авто

    # Toggle light mode 
    - media: "(prefers-color-scheme: light)"       
      scheme: default
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-7
        name: Испепели мои глаза!

    # Toggle dark mode  
    - media: "(prefers-color-scheme: dark)"      
      scheme: slate
      #primary: blue
      #accent: teal
      toggle:
        icon: material/brightness-4
        name: Я люблю свои глаза!

  font:
    code: Jet Brains Mono

  features:
    - navigation.instant
    #- navigation.sections # prevents collapsible sections
    - navigation.indexes # section index pages
    - navigation.expand #expands sections by default
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.pruning
    - navigation.path
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - toc.follow
  # insiders only
  #   - search.suggest

plugins:
  search:
    lang: 
      - ru
      - en

markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight: # code highlighting
      linenums: true
  - pymdownx.tabbed # enables tabs for embedded blocks
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2023 &copy; TheSt1tch - Licensed under GPLv3

extra:
  status:
    new: Recently added
    deprecated: Deprecated